# Generated by Django 3.0.5 on 2020-05-08 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incendies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moyensmobilise',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='wilaya',
            name='daira',
        ),
        migrations.AddField(
            model_name='commune',
            name='CodePostal',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='especesincendie',
            name='sup',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='nombre',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='typeformationincendie',
            name='sup',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='incendie',
            name='dateExt',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='incendie',
            name='heureDepart',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='incendie',
            name='heureIntervention',
            field=models.DateTimeField(blank=True),
        ),
    ]
