# Generated by Django 3.0.5 on 2020-05-09 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incendies', '0004_auto_20200509_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incendie',
            name='dateExt',
            field=models.DateTimeField(blank=True, default='2020-06-01 00:00:00', null=True),
        ),
    ]
