# Generated by Django 3.0.5 on 2020-05-10 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incendies', '0005_auto_20200509_0115'),
    ]

    operations = [
        
        migrations.RemoveField(
            model_name='incendie',
            name='supEstime',
        ),
        migrations.RemoveField(
            model_name='incendie',
            name='supPlani',
        ),
        migrations.AlterField(
            model_name='incendie',
            name='heureDepart',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='incendie',
            name='heureIntervention',
            field=models.DateField(blank=True),
        ),
    ]
