# Generated by Django 3.0.5 on 2020-05-10 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incendies', '0006_auto_20200510_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incendie',
            name='heureDepart',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='incendie',
            name='heureIntervention',
            field=models.DateTimeField(blank=True),
        ),
    ]
