# Generated by Django 3.0.5 on 2020-05-11 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incendies', '0008_auto_20200510_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incendie',
            name='heureDepart',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='incendie',
            name='heureIntervention',
            field=models.DateTimeField(null=True),
        ),
    ]
