# Generated by Django 3.0.5 on 2020-05-14 01:21
from django.contrib.postgres.operations import CreateExtension

from django.db import migrations, models
import django.contrib.gis.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('incendies', '0011_auto_20200512_0017'),
    ]

    operations = [
         
        
        migrations.AlterField(
            model_name='incendie',
            name='Commentaires',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='incendie',
            name='heureDepart',
            field=models.DateTimeField(blank=True, default='2020-06-01 00:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='incendie',
            name='heureIntervention',
            field=models.DateTimeField(blank=True, default='2020-06-01 00:00:00', null=True),
        ),
    ]
