# Generated by Django 3.0.5 on 2020-05-19 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incendies', '0012_auto_20200514_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='incendie',
            name='wilaya',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='incendies.Wilaya'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incendie',
            name='forets',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='incendie',
            name='lieudit',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
