# Generated by Django 3.0.5 on 2020-05-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incendies', '0016_auto_20200519_0246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incendie',
            name='wilaya',
        ),
        
    ]
