# Generated by Django 3.0.5 on 2020-05-20 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incendies', '0017_auto_20200519_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='incendie',
            name='wilaya',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='incendies.Wilaya'),
            preserve_default=False,
        ),
    ]
