# Generated by Django 3.0.5 on 2020-05-26 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incendies', '0020_auto_20200524_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeformationincendie',
            name='espece',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='incendies.Espece'),
            preserve_default=False,
        ),
    ]
