# Generated by Django 3.0.5 on 2020-05-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incendies', '0023_auto_20200526_0244'),
    ]

    operations = [
         
        migrations.AddField(
            model_name='wilaya',
            name='Lat',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='wilaya',
            name='Long',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=8, null=True),
        ),
    ]
