# Generated by Django 3.0.5 on 2020-05-27 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incendies', '0025_auto_20200528_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='espece',
            name='typeformation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='incendies.Typeformation'),
        ),
        migrations.AddField(
            model_name='moyensmateriel',
            name='moyenshumain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='incendies.Moyenshumain'),
        ),
    ]
