# Generated by Django 3.0.5 on 2020-05-28 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incendies', '0026_auto_20200528_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervention',
            name='moyensmateriel',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='nombremateriel',
        ),
        migrations.CreateModel(
            name='Moyen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombremateriel', models.IntegerField(default=0, null=True)),
                ('incendie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incendies.Incendie')),
                ('moyensmateriel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='incendies.Moyensmateriel')),
                ('organisme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incendies.Organisme')),
            ],
        ),
    ]
