# Generated by Django 3.0.5 on 2020-06-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incendies', '0027_auto_20200528_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='incendie',
            name='dateDepart',
            field=models.DateField(default='2020-06-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incendie',
            name='dateIntervention',
            field=models.DateField(default='2020-06-01',blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incendie',
            name='heureExt',
            field=models.TimeField(default='00:00:00',blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incendie',
            name='dateExt',
            field=models.DateField(default='2020-06-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incendie',
            name='heureDepart',
            field=models.TimeField(default='00:00:00',blank=True, null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incendie',
            name='heureIntervention',
            field=models.TimeField(default='00:00:00',blank=True, null=True),
        ),
    ]
