# Generated by Django 3.0.5 on 2020-06-17 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incendies', '0031_auto_20200606_2142'),
    
    ]
