# Generated by Django 3.0.5 on 2020-06-13 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incendies', '0031_auto_20200606_2142'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Canton',
        ),
        migrations.DeleteModel(
            name='Foret_recreative',
        ),
        migrations.DeleteModel(
            name='Limite_commune',
        ),
        migrations.DeleteModel(
            name='Localites',
        ),
        migrations.DeleteModel(
            name='Parcellaire_perimetre',
        ),
        migrations.DeleteModel(
            name='Perimetre',
        ),
        migrations.DeleteModel(
            name='Reboisement',
        ),
    ]
