# Generated by Django 3.0.5 on 2020-06-18 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incendies', '0033_limite_commune'),
    ]

    operations = [
        migrations.RenameField(
            model_name='limite_commune',
            old_name='name',
            new_name='commune',
        ),
    ]
